version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    # environment:
    #   - REACT_APP_BACKEND_URL="*"
  backend:
    container_name: backend
    build: ./backend
    depends_on:
    - redis
    - postgres
    environment:
      - REDIS_HOST=Redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      # - REQUEST_ORIGIN="*"
  Redis:
    container_name: Redis
    image: redis
    restart: unless-stopped
  db:
    container_name: db
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
  proxy: 
    container_name: proxy
    depends_on:
      - frontend
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf