# Make sure you have java 8 installed
From openjdk:8
COPY ./spring-example-project /usr/src/app
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y dos2unix
RUN dos2unix mvnw
RUN ./mvnw package
EXPOSE 8080
CMD java -jar ./target/docker-example-1.1.3.jar
